"""Updated with safety checks

Revision ID: 582f9451ef88
Revises: a3e7c9d41f2b
Create Date: 2026-08-02 15:55:07.294434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582f9451ef88'
down_revision: Union[str, None] = 'a3e7c9d41f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
