"""add_student_auto_bootstrap_fields

Revision ID: d6f16fd85e7c
Revises: None
Create Date: 2026-08-02 10:46:32.985812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f16fd85e7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_path', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_idempotency_key', 'idempotency_records', ['idempotency_key'], unique=True)
    op.create_table('payment_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'payment_audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_created_at', 'payment_audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'payment_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('platform_commission_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), server_default='15.00', nullable=False),
    sa.Column('fixed_fee', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fixed_fee >= 0', name='ck_commission_fixed_fee_non_negative'),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name='ck_commission_percentage_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commission_rules_is_active', 'platform_commission_rules', ['is_active'], unique=False)
    op.create_table('reconciliation_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_wallets_checked', sa.Integer(), nullable=False),
    sa.Column('discrepancies_count', sa.Integer(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_run_at', 'reconciliation_reports', ['run_at'], unique=False)
    op.create_index('ix_reconciliation_status', 'reconciliation_reports', ['status'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('license_number', sa.String(length=128), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('availability_status', sa.String(length=32), server_default='unavailable', nullable=False),
    sa.Column('online_status', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('current_vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_trips', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancellation_rate', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('acceptance_rate', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('earnings', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability_status IN ('available', 'unavailable', 'busy')", name='ck_drivers_availability_status'),
    sa.CheckConstraint("verification_status IN ('draft', 'submitted', 'pending_review', 'pending', 'verified', 'approved', 'rejected')", name='ck_drivers_verification_status'),
    sa.CheckConstraint('acceptance_rate >= 0 AND acceptance_rate <= 100', name='ck_drivers_acceptance_rate_range'),
    sa.CheckConstraint('cancellation_rate >= 0 AND cancellation_rate <= 100', name='ck_drivers_cancellation_rate_range'),
    sa.CheckConstraint('earnings >= 0', name='ck_drivers_earnings_non_negative'),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_drivers_rating_range'),
    sa.CheckConstraint('total_trips >= 0', name='ck_drivers_total_trips_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number', name='uq_drivers_license_number'),
    sa.UniqueConstraint('user_id', name='uq_drivers_user_id')
    )
    op.create_index('ix_drivers_availability_online', 'drivers', ['availability_status', 'online_status'], unique=False)
    op.create_index('ix_drivers_license_number', 'drivers', ['license_number'], unique=False)
    op.create_index('ix_drivers_user_id', 'drivers', ['user_id'], unique=False)
    op.create_index('ix_drivers_verification_status', 'drivers', ['verification_status'], unique=False)
    op.create_table('kyc_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('applicant_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("applicant_type IN ('student', 'driver')", name='ck_kyc_applications_applicant_type'),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'PENDING', 'UNDER_REVIEW')", name='ck_kyc_applications_status'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kyc_applications_applicant_type_status', 'kyc_applications', ['applicant_type', 'status'], unique=False)
    op.create_index('ix_kyc_applications_status', 'kyc_applications', ['status'], unique=False)
    op.create_index('ix_kyc_applications_user_id', 'kyc_applications', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('student_number', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('profile_image', sa.String(length=2048), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=32), server_default='verified', nullable=False),
    sa.Column('preferred_pickup_location', sa.String(length=512), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_status IN ('pending', 'verified', 'rejected')", name='ck_students_verification_status'),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_students_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_number', name='uq_students_student_number'),
    sa.UniqueConstraint('user_id', name='uq_students_user_id')
    )
    op.create_index(op.f('ix_students_student_number'), 'students', ['student_number'], unique=True)
    op.create_index('ix_students_user_id', 'students', ['user_id'], unique=False)
    op.create_index('ix_students_verification_status', 'students', ['verification_status'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('account_status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_status IN ('active', 'inactive', 'suspended', 'deleted')", name='ck_user_profiles_account_status'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', name='uq_user_profiles_phone_number'),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id')
    )
    op.create_index('ix_user_profiles_account_status', 'user_profiles', ['account_status'], unique=False)
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('file_url', sa.String(length=2048), nullable=False),
    sa.Column('verification_status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_status IN ('DRAFT', 'SUBMITTED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'PENDING', 'UNDER_REVIEW')", name='ck_kyc_documents_verification_status'),
    sa.ForeignKeyConstraint(['application_id'], ['kyc_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kyc_documents_application_id', 'kyc_documents', ['application_id'], unique=False)
    op.create_index('ix_kyc_documents_type', 'kyc_documents', ['type'], unique=False)
    op.create_table('kyc_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=False),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('PENDING_REVIEW', 'UNDER_REVIEW', 'APPROVED', 'REJECTED')", name='ck_kyc_reviews_action'),
    sa.ForeignKeyConstraint(['application_id'], ['kyc_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kyc_reviews_application_id', 'kyc_reviews', ['application_id'], unique=False)
    op.create_index('ix_kyc_reviews_reviewer_id', 'kyc_reviews', ['reviewer_id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('pickup_location', sa.String(length=512), nullable=False),
    sa.Column('destination_location', sa.String(length=512), nullable=False),
    sa.Column('distance', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estimated_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='REQUESTED', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('REQUESTED', 'MATCHING', 'ACCEPTED', 'ARRIVING', 'STARTED', 'COMPLETED', 'CANCELLED')", name='ck_rides_status'),
    sa.CheckConstraint('distance >= 0', name='ck_rides_distance_non_negative'),
    sa.CheckConstraint('estimated_fare >= 0', name='ck_rides_estimated_fare_non_negative'),
    sa.CheckConstraint('final_fare IS NULL OR final_fare >= 0', name='ck_rides_final_fare_non_negative'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rides_driver_id', 'rides', ['driver_id'], unique=False)
    op.create_index('ix_rides_driver_status', 'rides', ['driver_id', 'status'], unique=False)
    op.create_index('ix_rides_requested_at', 'rides', ['requested_at'], unique=False)
    op.create_index('ix_rides_status', 'rides', ['status'], unique=False)
    op.create_index('ix_rides_student_id', 'rides', ['student_id'], unique=False)
    op.create_index('ix_rides_student_status', 'rides', ['student_id', 'status'], unique=False)
    op.create_table('student_favourite_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'name', name='uq_student_favourite_locations_student_name')
    )
    op.create_index('ix_student_favourite_locations_student_id', 'student_favourite_locations', ['student_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('registration_number', sa.String(length=64), nullable=False),
    sa.Column('make', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), server_default='car', nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='4', nullable=False),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('registration_document', sa.String(length=2048), nullable=True),
    sa.Column('insurance_document', sa.String(length=2048), nullable=True),
    sa.Column('roadworthy_document', sa.String(length=2048), nullable=True),
    sa.Column('inspection_status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("inspection_status IN ('draft', 'pending', 'approved', 'rejected')", name='ck_vehicles_inspection_status'),
    sa.CheckConstraint("vehicle_type IN ('car', 'van', 'motorcycle', 'bus')", name='ck_vehicles_vehicle_type'),
    sa.CheckConstraint('year >= 1980', name='ck_vehicles_year_min'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', name='uq_vehicles_driver_id_mvp'),
    sa.UniqueConstraint('registration_number', name='uq_vehicles_registration_number')
    )
    op.create_index('ix_vehicles_driver_id', 'vehicles', ['driver_id'], unique=False)
    op.create_index('ix_vehicles_driver_status', 'vehicles', ['driver_id', 'inspection_status'], unique=False)
    op.create_index('ix_vehicles_inspection_status', 'vehicles', ['inspection_status'], unique=False)
    op.create_index('ix_vehicles_registration_number', 'vehicles', ['registration_number'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('wallet_type', sa.String(length=32), server_default='USER', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('locked_balance', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'FROZEN', 'CLOSED')", name='ck_wallets_status'),
    sa.CheckConstraint("wallet_type IN ('USER', 'DRIVER', 'PLATFORM')", name='ck_wallets_wallet_type'),
    sa.CheckConstraint('balance >= 0', name='ck_wallets_balance_non_negative'),
    sa.CheckConstraint('locked_balance >= 0', name='ck_wallets_locked_balance_non_negative'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallets_driver_id', 'wallets', ['driver_id'], unique=False)
    op.create_index('ix_wallets_type_status', 'wallets', ['wallet_type', 'status'], unique=False)
    op.create_index('ix_wallets_user_id', 'wallets', ['user_id'], unique=False)
    op.create_table('driver_earnings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('gross_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_deducted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('net_earning', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payout_status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('payout_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payout_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')", name='ck_driver_earnings_payout_status'),
    sa.CheckConstraint('gross_fare >= 0', name='ck_driver_earnings_gross_non_negative'),
    sa.CheckConstraint('net_earning >= 0', name='ck_driver_earnings_net_non_negative'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    op.create_index('ix_driver_earnings_driver_id', 'driver_earnings', ['driver_id'], unique=False)
    op.create_index('ix_driver_earnings_payout_status', 'driver_earnings', ['payout_status'], unique=False)
    op.create_index('ix_driver_earnings_ride_id', 'driver_earnings', ['ride_id'], unique=True)
    op.create_table('ride_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_commission', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('driver_net_earnings', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'AUTHORIZED', 'CAPTURED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'FAILED', 'CANCELLED')", name='ck_ride_payments_status'),
    sa.CheckConstraint('driver_net_earnings >= 0', name='ck_ride_payments_net_non_negative'),
    sa.CheckConstraint('gross_amount >= 0', name='ck_ride_payments_gross_non_negative'),
    sa.CheckConstraint('platform_commission >= 0', name='ck_ride_payments_commission_non_negative'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    op.create_index('ix_ride_payments_driver_id', 'ride_payments', ['driver_id'], unique=False)
    op.create_index('ix_ride_payments_idempotency', 'ride_payments', ['idempotency_key'], unique=False)
    op.create_index('ix_ride_payments_ride_id', 'ride_payments', ['ride_id'], unique=True)
    op.create_index('ix_ride_payments_status', 'ride_payments', ['status'], unique=False)
    op.create_index('ix_ride_payments_student_id', 'ride_payments', ['student_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('source_wallet_id', sa.String(length=36), nullable=True),
    sa.Column('target_wallet_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('ride_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVERSED')", name='ck_transactions_status'),
    sa.CheckConstraint("transaction_type IN ('DEPOSIT', 'WITHDRAWAL', 'RIDE_PAYMENT', 'DRIVER_PAYOUT', 'REFUND', 'PLATFORM_COMMISSION', 'TRANSFER', 'SYSTEM_ADJUSTMENT')", name='ck_transactions_type'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.CheckConstraint('fee_amount >= 0', name='ck_transactions_fee_non_negative'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('ix_transactions_idempotency_key', 'transactions', ['idempotency_key'], unique=False)
    op.create_index('ix_transactions_reference', 'transactions', ['reference'], unique=True)
    op.create_index('ix_transactions_ride_id', 'transactions', ['ride_id'], unique=False)
    op.create_index('ix_transactions_source_wallet', 'transactions', ['source_wallet_id'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_transactions_target_wallet', 'transactions', ['target_wallet_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'COMPLETED', 'FAILED')", name='ck_refunds_status'),
    sa.CheckConstraint('amount > 0', name='ck_refunds_amount_positive'),
    sa.ForeignKeyConstraint(['payment_id'], ['ride_payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refunds_idempotency_key', 'refunds', ['idempotency_key'], unique=False)
    op.create_index('ix_refunds_payment_id', 'refunds', ['payment_id'], unique=False)
    op.create_index('ix_refunds_status', 'refunds', ['status'], unique=False)
    op.create_index('ix_refunds_transaction_id', 'refunds', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refunds_transaction_id', table_name='refunds')
    op.drop_index('ix_refunds_status', table_name='refunds')
    op.drop_index('ix_refunds_payment_id', table_name='refunds')
    op.drop_index('ix_refunds_idempotency_key', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_transactions_target_wallet', table_name='transactions')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_source_wallet', table_name='transactions')
    op.drop_index('ix_transactions_ride_id', table_name='transactions')
    op.drop_index('ix_transactions_reference', table_name='transactions')
    op.drop_index('ix_transactions_idempotency_key', table_name='transactions')
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_ride_payments_student_id', table_name='ride_payments')
    op.drop_index('ix_ride_payments_status', table_name='ride_payments')
    op.drop_index('ix_ride_payments_ride_id', table_name='ride_payments')
    op.drop_index('ix_ride_payments_idempotency', table_name='ride_payments')
    op.drop_index('ix_ride_payments_driver_id', table_name='ride_payments')
    op.drop_table('ride_payments')
    op.drop_index('ix_driver_earnings_ride_id', table_name='driver_earnings')
    op.drop_index('ix_driver_earnings_payout_status', table_name='driver_earnings')
    op.drop_index('ix_driver_earnings_driver_id', table_name='driver_earnings')
    op.drop_table('driver_earnings')
    op.drop_index('ix_wallets_user_id', table_name='wallets')
    op.drop_index('ix_wallets_type_status', table_name='wallets')
    op.drop_index('ix_wallets_driver_id', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('ix_vehicles_registration_number', table_name='vehicles')
    op.drop_index('ix_vehicles_inspection_status', table_name='vehicles')
    op.drop_index('ix_vehicles_driver_status', table_name='vehicles')
    op.drop_index('ix_vehicles_driver_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_student_favourite_locations_student_id', table_name='student_favourite_locations')
    op.drop_table('student_favourite_locations')
    op.drop_index('ix_rides_student_status', table_name='rides')
    op.drop_index('ix_rides_student_id', table_name='rides')
    op.drop_index('ix_rides_status', table_name='rides')
    op.drop_index('ix_rides_requested_at', table_name='rides')
    op.drop_index('ix_rides_driver_status', table_name='rides')
    op.drop_index('ix_rides_driver_id', table_name='rides')
    op.drop_table('rides')
    op.drop_index('ix_kyc_reviews_reviewer_id', table_name='kyc_reviews')
    op.drop_index('ix_kyc_reviews_application_id', table_name='kyc_reviews')
    op.drop_table('kyc_reviews')
    op.drop_index('ix_kyc_documents_type', table_name='kyc_documents')
    op.drop_index('ix_kyc_documents_application_id', table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.drop_index('ix_user_profiles_account_status', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_students_verification_status', table_name='students')
    op.drop_index('ix_students_user_id', table_name='students')
    op.drop_index(op.f('ix_students_student_number'), table_name='students')
    op.drop_table('students')
    op.drop_index('ix_kyc_applications_user_id', table_name='kyc_applications')
    op.drop_index('ix_kyc_applications_status', table_name='kyc_applications')
    op.drop_index('ix_kyc_applications_applicant_type_status', table_name='kyc_applications')
    op.drop_table('kyc_applications')
    op.drop_index('ix_drivers_verification_status', table_name='drivers')
    op.drop_index('ix_drivers_user_id', table_name='drivers')
    op.drop_index('ix_drivers_license_number', table_name='drivers')
    op.drop_index('ix_drivers_availability_online', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('ix_reconciliation_status', table_name='reconciliation_reports')
    op.drop_index('ix_reconciliation_run_at', table_name='reconciliation_reports')
    op.drop_table('reconciliation_reports')
    op.drop_index('ix_commission_rules_is_active', table_name='platform_commission_rules')
    op.drop_table('platform_commission_rules')
    op.drop_index('ix_audit_entity', table_name='payment_audit_logs')
    op.drop_index('ix_audit_created_at', table_name='payment_audit_logs')
    op.drop_index('ix_audit_actor', table_name='payment_audit_logs')
    op.drop_table('payment_audit_logs')
    op.drop_index('ix_idempotency_key', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
